### ISSUE TITLE
capacitor 2X0.1uf and question about non-functionning PSU

### ISSUE THREAD

**Issue by Hjertesvikt** [mdehling/vs3100-psu-repair#1]
Thanks for this incredible resource! I used it to replace all mentioned capacitors in the PSU of my VaxStation 3100 model 38
I have two questions:
1. There is a big square capacitor in my PSU which is labelled 2X0.1uF => Is it also to change?
2. The Leds of my VaxStation are all red at most startups so the station is mostly useless. 

(edit)
I found the pinout of the PSU:
![image](https://user-images.githubusercontent.com/28840268/182032367-63a8ae97-2562-4a0c-8a34-67e5906cd459.png)
There are two problems (at least):
a) pin 13 is at -6volts  (instead of -9V)
b) pin 14 is at 2,75 volts (instead of -9V)

Any suggestion?

Many thanks!

Jean-Pierre from France

**Comment by mdehling** [comment]
Bonjour Jean-Pierre!

thanks a lot for your message - I'm glad this is helpful for someone out there!

The X2 capacitors are RIFA brand safety capacitors.  If you google for RIFA capacitor you'll find lots of horror stories about them going up in smoke.  I haven't replaced them in the PSUs for my VAXstations because they looked ok (no visible cracks on the outside.)  But I feel like at this point I should probably mention that I am not an electrical engineer, so you might want to ask someone more knowledgeable for advice ;-)

Your voltages could be correct maybe.  I *think* you're supposed to measure pins 13/14 against each other to get -9V, not against GND?  Unfortunately I am currently very far away from my VAXstations and have no way to verify this for you.

Did you measure the voltages with a load (e.g., the mainboard) connected?  This is important as they could be okay but dip as soon as there is a load on the PSU.

If the voltages are correct even under load, then I would suspect mainboard issues.  There is a battery pack in the VAXstation and I'm sure it must have leaked.  Have you cleaned the mainboard of any residue?  It is possible that the memory chips in the corner closest to the battery pack have been affected.

You don't happen to have another working VAXstation or know someone with one nearby?  By far the easiest way to narrow down the problem is to swap parts with a known-good unit...

I hope you find the issue and are able to fix it.  Good Luck!

**Comment by Hjertesvikt** [comment]
Many thanks for the quick answer and the right advice!

You are right, when measured between pins 13/14 I get 9v. 
I used one of those modern cheap oscilloscopes and pins 13/14 output looks like it was unfiltered: There is a modulation at ~104KHz with an amplitude of several volts on these pins.

There are suspicious "greasy" traces around the daughter board where is C15 (on the left part on your schematics). A few resistances do not look so healthy.
And it looks like the metal part just below it was stained but cleaned later.
Yet the wires corresponding to pins 13/14 go through some inductance, then toward the C6/C7 area which doesn't look connected to the left daughter board.

My VaxStation was bought on ebay, and the seller told me they have cleaned it, and changed the battery. The battery pack looks indeed recent but as you warned, just below it there is also a stain on the metal part, but it looks as well having been cleaned and the memory boards look OK. When I received the station it was booting, so this failure happened after I received it.

I guess my next step will be to unsolder the daughter board and inspect/change some components. It will be a challenge as my eyesight is weaker and my hands are shaking a bit :-)

Many thanks for your invaluable help!

Jean-Pierre

**Comment by toncho11** [comment]
Hi,

So pin 7 brown is a range? Above it says between +3.5 and 5.25? Kind of strange. Do you know what is it for?

**Comment by JPLeRouzic** [comment]
> Hi,
> 
> So pin 7 brown is a range? Above it says between +3.5 and 5.25? Kind of strange. Do you know what is it for?

I may be wrong and I do not have anymore this VaxStation, but I think it's DCOK, a kind of "power good" signal sent from the PSU to the motherboard.
https://forum.vcfed.org/index.php?threads/vaxstation-issues.40373/#post-1285894

![image](https://github.com/user-attachments/assets/1e5bbc86-5d45-4235-9089-92de657756e7)

**Comment by toncho11** [comment]
Thanks!!!

**Comment by toncho11** [comment]
Hi/Bonjour,

I changed the capacitors, but I have a strange behavior. 
Sometimes the PSU starts with alternating voltages where it goes between low and high every for example 500ms. I see the multimeter changing and the fans accelerating and cutting power resulting in a speed that is two times slower than normal. You can hear the non constant spin from the fans.
And sometimes it works perfectly with all voltages as expected.

Maybe it needs a load to always work correctly? I attached a hard drive to the PSU and will test a cold start with empty capacitors later.
